apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hospital
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: hospital_db
  DB_USER: hospital_user
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CSRF_TRUSTED_ORIGINS: "http://13.48.214.136:30080"