apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  namespace: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: ghcr.io/martahentosh/hospital-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DEBUG
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEY
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CSRF_TRUSTED_ORIGINS
          volumeMounts:
            - mountPath: /app/media
              name: media-storage
            - mountPath: /app/staticfiles
              name: static-storage
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-pvc